services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    # Builda a imagem do backend
    build: ./backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --access-logfile -
    volumes:
      - staticfiles_data:/code/staticfiles
      - "${COMPRAS_PATH}:/code/media"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - BACKEND_HOST=backend
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  nginx:
    # Builda a imagem (que contém o Frontend compilado)
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot_data:/etc/letsencrypt
      - certbot_webroot:/var/www/certbot
      - staticfiles_data:/code/staticfiles:ro
      - "${COMPRAS_PATH}:/code/media:ro"
      # TRUQUE: Usamos o init.conf primeiro para o NGINX não cair
      - ./nginx/site.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_data:/etc/letsencrypt
      - certbot_webroot:/var/www/certbot
    # Comando manual para não ficar tentando renovar sem certificado
    command: echo "Aguardando comando manual..."
    networks:
      - app-network

  # Sync worker comentado por enquanto para evitar erros se não tiver rclone config
  # sync-worker:
  #   ...

networks:
  app-network:

volumes:
  db_data:
  staticfiles_data:
  certbot_data:
  certbot_webroot:
